apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "client-stack.fullname" . }}-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - {{ .Values.global.domain }}
      secretName: tls-{{ .Values.global.domain | replace "." "-" }}
  rules:
    - host: {{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "frontend.fullname" . }}
                port:
                  number: {{ .Values.frontend.service.port }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "backend.fullname" . }}
                port:
                  number: {{ .Values.backend.service.port }}
          - path: /phpmyadmin
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-phpmyadmin
                port:
                  number: 80
