apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          command: ["/bin/sh","-c"]
          args:
            - >
              npm run migration
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
