apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secrets
  labels:
    {{ include "backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.secrets }}
  {{- range $k, $v := . }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- end }}
