apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  DATABASE_PASSWORD: "{{ .Values.secrets.mysqlRootPassword }}"
  REDIS_PASSWORD: "{{ .Values.secrets.redisPassword }}"
  ELASTIC_PASSWORD: "{{ .Values.secrets.elasticPassword }}"
  APP_SESSION_SECRET: "{{ .Values.secrets.appSessionSecret }}"