apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-config
  namespace: {{ .Release.Namespace }}
data:
{{- range $key, $value := .Values.env }}
  {{- if not (or (hasSuffix "_PASSWORD" $key) (eq $key "APP_SESSION_SECRET")) }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
