apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          ports:
            - containerPort: {{ .Values.env.APP_PORT | int }}
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - port: {{ .Values.env.APP_PORT | int }}
      targetPort: {{ .Values.env.APP_PORT | int }}
  selector:
    app: backend
