{{- if and .Values.image .Values.image.repository }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-backend-migrate
  labels:
    {{ include "backend.labels" . | nindent 4 }}
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        {{ include "backend.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          command: ["/bin/sh","-c"]
          args: ["npm run migration"]
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-backend-config
            - secretRef:
                name: {{ .Release.Name }}-backend-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
{{- end }}
