apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
{{- range $key, $value := .Values.env }}
  {{- if or (hasSuffix "_PASSWORD" $key) (eq $key "APP_SESSION_SECRET") }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
