apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-ssl-config
  namespace: traefik-system
data:
  traefik.yml: |
    api:
      dashboard: true
      insecure: false
    entryPoints:
      web:
        address: ":80"
        http:
          redirections:
            entrypoint:
              to: websecure
              scheme: https
      websecure:
        address: ":443"
    certificatesResolvers:
      default:
        tls:
          certificates:
            - certFile: /certs/blog-cert.pem
              keyFile: /certs/blog-key.pem
    providers:
      kubernetes:
        ingressClass: traefik
    log:
      level: INFO
    accessLog: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: traefik-system
  labels:
    app.kubernetes.io/name: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
  template:
    metadata:
      labels:
        app.kubernetes.io/name: traefik
    spec:
      containers:
      - name: traefik
        image: traefik:v3.5.2
        args:
        - --configfile=/etc/traefik/traefik.yml
        ports:
        - name: web
          containerPort: 80
        - name: websecure
          containerPort: 443
        - name: traefik
          containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /etc/traefik
        - name: certs
          mountPath: /certs
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: config
        configMap:
          name: traefik-ssl-config
      - name: certs
        secret:
          secretName: blog-ssl-cert
---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik-system
  labels:
    app.kubernetes.io/name: traefik
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 80
    targetPort: 80
    protocol: TCP
  - name: websecure
    port: 443
    targetPort: 443
    protocol: TCP
  - name: traefik
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/name: traefik


