apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  {{- $existing := (lookup "v1" "Secret" .Release.Namespace (printf "%s-secrets" .Release.Name)) }}
  {{- if $existing }}
  MYSQL_ROOT_PASSWORD: {{ b64dec (index $existing.data "MYSQL_ROOT_PASSWORD") }}
  MYSQL_DATABASE: {{ b64dec (index $existing.data "MYSQL_DATABASE") }}
  REDIS_PASSWORD: {{ b64dec (index $existing.data "REDIS_PASSWORD") | default (randAlphaNum 24) }}
  ELASTIC_PASSWORD: {{ b64dec (index $existing.data "ELASTIC_PASSWORD") | default (randAlphaNum 24) }}
  {{- else }}
  MYSQL_ROOT_PASSWORD: {{ randAlphaNum 24 | quote }}
  MYSQL_DATABASE: {{ printf "%s_db" .Values.clientId | quote }}
  REDIS_PASSWORD: {{ randAlphaNum 24 | quote }}
  ELASTIC_PASSWORD: {{ randAlphaNum 24 | quote }}
  {{- end }}