version: "3.9"

services:
  api:
    build: ./backend
    container_name: site-api
    env_file:
      - ./.env
    ports:
      - "3000:3000"    
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  web:
    build: ./frontend
    container_name: site-web
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped
