{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "blog-template.fullname" . }}-ingress
  namespace: {{ .Values.client.namespace }}
  labels:
    {{- include "blog-template.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    # Traefik specific annotations
    traefik.ingress.kubernetes.io/router.entrypoints: web{{- if .Values.ingress.tls.enabled }},websecure{{- end }}
    # Note: Using standard ingress rules instead of custom router rule
    {{- if .Values.ingress.tls.enabled }}
    traefik.ingress.kubernetes.io/router.tls: "true"
    {{- end }}
    # Load balancing
    traefik.ingress.kubernetes.io/service.loadbalancer.method: roundrobin
    traefik.ingress.kubernetes.io/service.loadbalancer.healthcheck.path: /health
    # Note: Middlewares removed to prevent routing issues
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.client.domain }}
    {{- if .Values.ingress.tls.secretName }}
    secretName: {{ .Values.ingress.tls.secretName }}
    {{- else }}
    secretName: {{ include "blog-template.fullname" . }}-tls
    {{- end }}
  {{- end }}
  rules:
  - host: {{ .Values.client.domain }}
    http:
      paths:
      # Frontend routes
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "blog-template.frontend.serviceName" . }}
            port:
              number: {{ .Values.ports.frontend.internal }}
      # Backend API routes
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ include "blog-template.backend.serviceName" . }}
            port:
              number: {{ .Values.ports.backend.internal }}
      # Health check endpoint
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: {{ include "blog-template.backend.serviceName" . }}
            port:
              number: {{ .Values.ports.backend.internal }}
{{- end }}
