{{- $mail := (.Values.mailcrab | default (dict "enabled" false "uiHostPrefix" "mail")) }}
{{- $res := (get .Values.resources "mailcrab" | default dict) }}
{{- if $mail.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mailcrab-ui
spec:
  ports:
    - name: http
      port: {{ $mail.ports.ui }}
      targetPort: {{ $mail.ports.ui }}
  selector:
    app: {{ .Release.Name }}-mailcrab
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mailcrab-smtp
spec:
  ports:
    - name: smtp
      port: {{ $mail.ports.smtp }}
      targetPort: {{ $mail.ports.smtp }}
  selector:
    app: {{ .Release.Name }}-mailcrab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mailcrab
spec:
  replicas: {{ if .Values.suspended }}0{{ else }}1{{ end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mailcrab
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mailcrab
    spec:
      containers:
        - name: mailcrab
          image: "{{ $mail.image.repository }}:{{ $mail.image.tag }}"
          ports:
            - containerPort: {{ $mail.ports.ui }}
            - containerPort: {{ $mail.ports.smtp }}
          resources:
{{- toYaml $res | nindent 12 }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-mailcrab
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
    - host: {{ $mail.uiHostPrefix }}.{{ .Values.clientId }}.{{ .Values.baseDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-mailcrab-ui
                port:
                  number: {{ $mail.ports.ui }}
{{- end }}