apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-envfile
type: Opaque
stringData:
  .env: |
    APP_ENV=production
    APP_TIMEZONE=UTC
    {{- $sec := (lookup "v1" "Secret" .Release.Namespace (printf "%s-secrets" .Release.Name)) }}
    DATABASE_NAME={{- if and $sec $sec.data (index $sec.data "MYSQL_DATABASE") -}}{{ b64dec (index $sec.data "MYSQL_DATABASE") }}{{- else -}}{{ printf "%s_db" .Values.clientId }}{{- end }}
    DATABASE_PASSWORD={{- if and $sec $sec.data (index $sec.data "MYSQL_ROOT_PASSWORD") -}}{{ b64dec (index $sec.data "MYSQL_ROOT_PASSWORD") }}{{- else -}}{{ randAlphaNum 8 }}{{- end }}
    REDIS_PASSWORD={{- if and $sec $sec.data (index $sec.data "REDIS_PASSWORD") -}}{{ b64dec (index $sec.data "REDIS_PASSWORD") }}{{- else -}}{{ randAlphaNum 8 }}{{- end }}