apiVersion: v2
name: client-stack
description: Client stack (backend, frontend, DB, cache, search)
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: mysql
    version: 9.16.0
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: 18.6.0
    repository: https://charts.bitnami.com/bitnami
  - name: opensearch
    version: 2.20.0
    repository: https://opensearch-project.github.io/helm-charts/
  - name: backend
    version: 0.1.0
    repository: "file://charts/backend"
  - name: frontend
    version: 0.1.0
    repository: "file://charts/frontend"