global:
  domain: ""          # override per client
  clientName: ""      # release/namespace name

secrets:
  mysqlRootPassword: "changeme"
  redisPassword: "changeme"
  elasticPassword: "changeme"
  appSessionSecret: "changeme"

backend:
  image:
    repository: nginx
    tag: latest
  service:
    port: 3000
  env: {}

frontend:
  image:
    repository: nginx
    tag: alpine
  service:
    port: 80

mysql:
  auth:
    rootPassword: changeme
    database: appdb
  primary:
    persistence:
      enabled: true
      size: 5Gi

redis:
  auth:
    password: changeme
  master:
    persistence:
      enabled: true
      size: 2Gi
  replica:
    replicaCount: 0

opensearch:
  clusterName: client-os
  replicas: 1
  minimumMasterNodes: 1
  singleNode: true
  persistence:
    enabled: true
    size: 5Gi
  resources:
    requests:
      cpu: "100m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

phpmyadmin:
  enabled: true
  db:
    host: mysql
    port: 3306
    user: root
    password: changeme
  service:
    type: ClusterIP
    port: 80
