apiVersion: v1
kind: Secret
metadata:
  name: client-a-secrets
  namespace: client-a
type: Opaque
stringData:
  DATABASE_PASSWORD: "your-db-password"
  REDIS_PASSWORD: "your-redis-password"
  ELASTIC_PASSWORD: "your-elastic-password"
