# k8s/es01-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: es01
  namespace: client-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es01
  template:
    metadata:
      labels:
        app: es01
    spec:
      containers:
      - name: es01
        image: docker.elastic.co/elasticsearch/elasticsearch-wolfi:8.18.1
        env:
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: client-a-secrets
              key: ELASTIC_PASSWORD
        - name: ES_JAVA_OPTS
          value: "-Xms2g -Xmx2g"
        ports:
        - containerPort: 9200
        volumeMounts:
        - name: es01-storage
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: es01-storage
        persistentVolumeClaim:
          claimName: es01-pvc
---

