apiVersion: v1
kind: Service
metadata:
  name: mailcrab
  namespace: client-a
spec:
  selector:
    app: mailcrab
  ports:
  - name: smtp
    port: 1025
    targetPort: 1025
  - name: web-ui
    port: 8025
    targetPort: 1080
  type: ClusterIP
