apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: client-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: mysql
        image: mysql:8.4.5
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: client-a-secrets
              key: DATABASE_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: client-a-config
              key: DATABASE_NAME
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: client-a-config
              key: APP_TIMEZONE
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
