---
# ───────────────────────────────────────────────
# 01_k3s.yml – Install and Bootstrap K3s Cluster
# ───────────────────────────────────────────────

- name: Install dependencies on all remote nodes
  hosts: k3s_master:k3s_agents
  become: yes
  tasks:
    - name: Ensure required packages are installed
      apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
          - software-properties-common
        state: present
        update_cache: yes

# ───────────────────────────────────────────────
# MASTER NODE SETUP
# ───────────────────────────────────────────────
- name: Install K3s master
  hosts: k3s_master
  become: yes
  tasks:
    - name: Install K3s server if not already present
      shell: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --write-kubeconfig-mode=644 --disable traefik" sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Wait for K3s API to be ready
      shell: k3s kubectl get nodes
      register: api_check
      retries: 20
      delay: 5
      until: api_check.rc == 0
      ignore_errors: false

    - name: Fetch kubeconfig from master
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: kubeconfig_master.yaml
        flat: yes
      register: kubeconfig_fetch

    - name: Replace localhost with master IP in kubeconfig
      delegate_to: localhost
      lineinfile:
        path: kubeconfig_master.yaml
        regexp: '127\.0\.0\.1'
        line: "{{ ansible_host }}"

    - name: Retrieve K3s cluster token
      shell: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      retries: 10
      delay: 3
      until: k3s_token.stdout != ""
      changed_when: false

    - name: Save cluster token for later
      set_fact:
        cluster_token: "{{ k3s_token.stdout }}"

# ───────────────────────────────────────────────
# AGENT NODE SETUP
# ───────────────────────────────────────────────
- name: Install K3s agents
  hosts: k3s_agents
  become: yes
  tasks:
    - name: Install K3s agent if not already present
      shell: |
        curl -sfL https://get.k3s.io | \
        K3S_URL="https://{{ hostvars[groups['k3s_master'][0]].ansible_host }}:6443" \
        K3S_TOKEN="{{ hostvars[groups['k3s_master'][0]].cluster_token }}" sh -
      args:
        creates: /usr/local/bin/k3s-agent

# ───────────────────────────────────────────────
# FINAL LOCAL MERGE
# ───────────────────────────────────────────────
- name: Merge and verify kubeconfig locally
  hosts: localhost
  vars:
    KUBECONFIG_LOCAL: kubeconfig_cluster.yaml
  tasks:
    - name: Copy master kubeconfig as cluster config
      copy:
        src: kubeconfig_master.yaml
        dest: "{{ KUBECONFIG_LOCAL }}"
        mode: '0600'

    - name: Verify that cluster nodes are Ready
      shell: kubectl --kubeconfig {{ KUBECONFIG_LOCAL }} get nodes
      register: nodes
      retries: 10
      delay: 6
      until: "'Ready' in nodes.stdout"
